Vagrant.configure("2") do |config|
  config.vm.box= "generic/ubuntu2004"

  config.vm.provider "qemu" do |qe|
  qe.arch = "aarch64"
    qe.cpu = "max"
    qe.machine = "virt,highmem=on"
    qe.advanced_network = true
  end

  config.vm.box_check_update = false

$enable_forwarding = <<-SHELL
  sudo sed -i 's/#net.ipv4.ip_forward=1/net.ipv4.ip_forward=1/g' /etc/sysctl.conf
  sudo sysctl -p
SHELL

config.vm.define "vm-a" do |a|
  a.vm.hostname = "vm-a"
  a.vm.provider "qemu" do  |qe| 
    qe.ssh_port = 50022 
  end

  a.vm.provision "shell", inline:  <<-SHELL
  sudo sed -i 's/#net.ipv4.ip_forward=1/net.ipv4.ip_forward=1/g' /etc/sysctl.conf
  sudo sysctl -p
  
  cat <<EOF | sudo tee /etc/netplan/50-vagrant.yaml
network:
  version: 2
  renderer: networkd
  dummy:
    eth1:
      addresses: [172.16.0.10/24]
    eth2:
      addresses: [192.168.100.10/24]
      routes:
        - to: 192.168.101.0/24
          via: 192.168.100.20
        - to: 192.168.102.0/24
          via: 192.168.100.30
EOF
      sudo chmod 600 /etc/netplan/50-vagrant.yaml
      sudo netplan apply

      cat <<EOF | sudo tee /etc/nginx/sites-available/mysite.local
server {
    listen 80;
    server_name mysite.local;
    location / {
        proxy_pass http://192.168.102.30:80;
        proxy_set_header Host \\$host;
        proxy_set_header X-Real-IP \\$remote_addr;
        proxy_set_header X-Forwarded-For \\$proxy_add_x_forwarded_for;
    }
}
EOF
        sudo ln -sf /etc/nginx/sites-available/mysite.local /etc/nginx/sites-enabled/
        sudo rm -f /etc/nginx/sites-enabled/default
        sudo systemctl restart nginx
      SHELL
   end

config.vm.define "vm-b" do |b|
  b.vm.hostname = "vm-b"
  b.vm.provider "qemu" do  |qe| 
    qe.ssh_port = 50023 
  end

  b.vm.provision "shell", inline:  <<-SHELL

  sudo apt-get update && sudo apt-get install -y mysql-server

  sudo sed -i 's?#net.ipv4.ip_forward=1/net.ipv4.ip_forward=1/g' /etc/sysctl.conf
  sudo sysctl -p

   cat <<EOF | sudo tee /etc/netplan/50-vagrant.yaml
network:
  version: 2
  renderer: networkd
  dummy:
    eth1:
      addresses: [192.168.101.20/24]
    eth2:
      addresses: [192.168.100.20/24]
      routes:   
        - to: default
          via: 192.168.100.10
EOF
      sudo chmod 600 /etc/netplan/50-vagrant.yaml
      sudo netplan apply
      
      sudo sed -i 's/bind-address.*/bind-address = 0.0.0.0/g' /ect/mysql/mysql.d
      sudo systemctl restart mysql

      sudo mysql -e "CREATE DATABASE IF NOT EXISTS wordpress DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;"
      sudo mysql -e "CREATE USER IF NOT EXISTS 'wp_user'@'%' IDENTIFIED BY 'password123';"
      sudo mysql -e "GRANT ALL PRIVILEGES ON wordpress.* TO 'wp_user'@''%';"
      sudo mysql -e "FLUSH PRIVILEGES;"
    SHELL

    b.vm.provision "shell", run: "always", inline:"sudo ip  link set eth0 down || true"
  end

config.vm.define "vm-c" do |c|
  c.vm.hostname = "vm-c"
  c.vm.provider "qemu" do |qe| 
    qe.ssh_port = 50024 
  end
   c.vm.provision "shell", inline:  <<-SHELL
    
  sudo apt-get update && sudo apt-get install -y apache2 php libapache2-mod-php wget unzip
      
  sudo sed -i 's?#net.ipv4.ip_forward=1/net.ipv4.ip_forward=1/g' /etc/sysctl.conf
  sudo sysctl -p

  cat <<EOF | sudo tee /etc/netplan/50-vagrant.yaml
network:
  version: 2
  renderer: networkd
  dummy:
    eth1:
      addresses: [192.168.102.30/24]
    eth2:
      addresses: [192.168.100.30/24]
      routes:
        - to: default
          via: 192.168.100.10
EOF
      sudo chmod 600 /etc/netplan/50-vagrant.yaml   
      sudo netplan apply
      
      cd /tmp && wget -q https://wordpress.org/latest.tar.gz
      tar -xzf latest.tar.gz
      sudo mkdir -p /var/www/html/wordpress
      sudo cp -r wordpress/* /var/www/html/wordpress/
      sudo chown -R www-data:www-data /var/www/html/wordpress

      sudo cp /var/www/html/wordpress/wp-config-sample.php
      sudo sed -i "s/database_name_here/wordpress/" /var/www/html/wordpress/wp-config.php
      sudo sed -i "s/username_here/wordpress/" /var/www/html/wordpress/wp-config.php
      sudo sed -i "s/password_here/password123/" /var/www/html/wordpress/wp-config.php
      sudo sed -i "s/localhost/192.168.101.20/" /var/www/html/wordpress/wp-config.php

      cat <<EOF | sudo tee /etc/apache2/sites-available/wordpress.conf
<VirtualHost *:80>
    ServerName mysite.local
    DocumentRoot /var/www/html/wordpress
    <Directory /var/www/html/wordpress/>
        AllowOverride All
        Require all granted
    </Directory>
</VirtualHost>
EOF

     sudo a2ensite wordpress.conf
     sudo a2dissite 000-default.conf
     sudo systemctl restart apache2
   SHELL
 end
end